export enum ComponentEnum {
  Input = '输入框',
  InputSearch = '搜索输入框',
  InputTextArea = '文本域',
  InputNumber = '数字输入框',
  Select_Aadio = '单选下拉框',
  Select_Checkbox = '多选下拉框',
  TreeSelect = '树形下拉框',
  Tree = '树形',
  Switch = '开关',
  RadioGroup = '单选按钮组',
  Checkbox = '复选框',
  CheckboxGroup = '复选框组',
  Cascader = '级联选择',
  Slider = '滑动输入条',
  Rate = '评分',
  DatePicker = '日期选择框',
  MonthPicker = '月份选择框',
  RangePicker = '日期范围选择框',
  WeekPicker = '周选择框',
  TimePicker = '时间选择框',
  Upload = '上传',
  Mentions = '提及',
  Divider = '分割线',
  CustomUpload = '自定义上传',
  TableSelect = '表格选择',
  TransferSelect = '穿梭框选择',
}
